version: '3.8'

networks:
  backend:

services:
  tbcdb:
    container_name: tbc-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123
    networks:
      - backend
    ports:
      - "18001:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
  tbcapi:
    container_name: tbc-api
    image: ${DOCKER_REGISTRY-}tbcdemowebapi
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    networks:
      - backend
    environment:
      - DB_HOST=tbcdb
      - DB_NAME=TbcDb
      - DB_USER=sa
      - DB_SA_PASSWORD=Admin123
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "443:443"
      - "80:80"